In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import os
import glob 
import re


## Leer los archivos .txt

In [31]:
files = glob.glob("C:/Users/Alexa/Documents/Data analisis HIGI python/ine/*.txt")
files

['C:/Users/Alexa/Documents/Data analisis HIGI python/ine\\DatosAbiertos-DERFE-pdln_edms_sexo_20190930.txt',
 'C:/Users/Alexa/Documents/Data analisis HIGI python/ine\\DatosAbiertos-DERFE-pdln_edms_sexo_20191031.txt',
 'C:/Users/Alexa/Documents/Data analisis HIGI python/ine\\DatosAbiertos-DERFE-pdln_edms_sexo_20191130.txt',
 'C:/Users/Alexa/Documents/Data analisis HIGI python/ine\\DatosAbiertos-DERFE-pdln_edms_sexo_20191231.txt',
 'C:/Users/Alexa/Documents/Data analisis HIGI python/ine\\DatosAbiertos-DERFE-pdln_edms_sexo_20200131_Nal_Ext.txt',
 'C:/Users/Alexa/Documents/Data analisis HIGI python/ine\\DatosAbiertos-DERFE-pdln_edms_sexo_20200229_Nal_Ext.txt',
 'C:/Users/Alexa/Documents/Data analisis HIGI python/ine\\DatosAbiertos-DERFE-pdln_edms_sexo_20200331_Nal_Ext.txt',
 'C:/Users/Alexa/Documents/Data analisis HIGI python/ine\\DatosAbiertos-DERFE-pdln_edms_sexo_20200430_Nal_Ext.txt',
 'C:/Users/Alexa/Documents/Data analisis HIGI python/ine\\DatosAbiertos-DERFE-pdln_edms_sexo_20200531_Na

In [32]:
date=[]
date_=[]
files_=[]

for i,file in enumerate(files):
    date.append(re.findall(r'\d+',file)[0])


temp=sorted(range(len(date)), key=date.__getitem__)

for i in temp:
    date_.append(date[i])
    print(date[i],files[i])
    files_.append(files[i])

20190630 C:/Users/Alexa/Documents/Data analisis HIGI python/ine\DERFE-DatosAbiertos-Pl_20190630.txt
20190731 C:/Users/Alexa/Documents/Data analisis HIGI python/ine\DERFE-DatosAbiertos-Pl_20190731.txt
20190831 C:/Users/Alexa/Documents/Data analisis HIGI python/ine\DERFE-DatosAbiertos-Pl_20190831.txt
20190930 C:/Users/Alexa/Documents/Data analisis HIGI python/ine\DatosAbiertos-DERFE-pdln_edms_sexo_20190930.txt
20191031 C:/Users/Alexa/Documents/Data analisis HIGI python/ine\DatosAbiertos-DERFE-pdln_edms_sexo_20191031.txt
20191130 C:/Users/Alexa/Documents/Data analisis HIGI python/ine\DatosAbiertos-DERFE-pdln_edms_sexo_20191130.txt
20191231 C:/Users/Alexa/Documents/Data analisis HIGI python/ine\DatosAbiertos-DERFE-pdln_edms_sexo_20191231.txt
20200131 C:/Users/Alexa/Documents/Data analisis HIGI python/ine\DatosAbiertos-DERFE-pdln_edms_sexo_20200131_Nal_Ext.txt
20200229 C:/Users/Alexa/Documents/Data analisis HIGI python/ine\DatosAbiertos-DERFE-pdln_edms_sexo_20200229_Nal_Ext.txt
20200331 C:/

#### Filtro para los diferentes tipos de headers en los archivos y  creacion de la lista nominal nacional 

In [33]:
for i,file in enumerate(files_):
    data=pd.read_csv(file)
    data=data[1:]
    data=data[data['ENTIDAD']==11][1:]
    mpo=data.groupby(['MUNICIPIO']).sum()
    if i==0 :
        if 'LISTA_NAL' in mpo.columns:
            df_mpo = pd.DataFrame(mpo['LISTA_NAL'])
        if 'LISTA_NACIONAL' in mpo.columns:
            df_mpo = pd.DataFrame(mpo['LISTA_NACIONAL'])
        if 'LISTA' in mpo.columns:
            df_mpo = pd.DataFrame(mpo['LISTA'])
    else:
        if 'LISTA_NAL' in mpo.columns:
            df_mpo[date_[i]]=mpo['LISTA_NAL']
        if 'LISTA_NACIONAL' in mpo.columns:
            df_mpo[date_[i]]=mpo['LISTA_NACIONAL']
        if 'LISTA' in mpo.columns:
            df_mpo[date_[i]]=mpo['LISTA']

D:\PythonConda\envs\main\lib\site-packages\IPython\core\interactiveshell.py:3169: DtypeWarning: Columns (7,8,9) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [34]:
df_mpo

LISTA  20190731  20190831  20190930  20191031  20191130  \
MUNICIPIO                                                              
1            66624     66974     67275     67427     67541     67450   
2            92979     93375     93738     94040     94139     93825   
3           126219    127148    127860    128446    128937    128731   
4            48883     49261     49434     49656     49787     49699   
5            66488     67064     67584     67868     68120     67992   
6             4201      4221      4183      4207      4228      4203   
7           372677    375386    377278    378361    379387    378139   
8            30673     31268     31394     31431     31546     31501   
9            59355     59789     60069     60267     60366     60337   
10            9135      9202      9248      9283      9315      9288   
11           73088     73435     73955     74256     74574     74297   
12           22958     23020     23094     23212     23288     23300   
13           18129     18191     18281     18343     18396     18303   
14          111277    112192    112769    113311    113789    113675   
15          136478    137629    138506    139096    139676    139382   
16           16701     16750     16767     16845     16890     16862   
17          415356    418486    420740    422390    423691    422665   
18           28432     28587     28707     28858     28921     28920   
19           40350     40558     40715     40842     40902     40795   
20         1113418   1122721   1129193   1133923   1138154   1136414   
21           42608     42987     43185     43380     43456     43433   
22           17766     17854     17930     18031     18109     18125   
23          123101    124014    124137    124650    124160    123825   
24           10652     10677     10713     10761     10795     10782   
25           54088     54480     54684     54907     55054     55055   
26           45105     45584     45781     45974     46145     46109   
27          210028    211209    212069    212781    213140    212706   
28           82647     83044     83231     83494     83556     83394   
29           27442     27665     27794     27934     27986     27964   
30           80728     81238     81663     82003     82168     82163   
31           91316     92001     92405     92714     92921     92945   
32           59512     59955     60279     60509     60695     60551   
33           88843     89510     89925     90167     90447     90169   
34            4399      4424      4403      4433      4458      4444   
35           60058     60381     60629     60975     61098     61027   
36            6439      6479      6482      6493      6499      6495   
37          134728    135909    136624    137162    137655    137397   
38           10034     10098     10170     10198     10240     10230   
39           30596     30781     30932     31068     31107     31001   
40           13128     13207     13253     13314     13225     13108   
41           48136     48542     48732     48972     49213     49128   
42          112730    113491    114029    114362    114729    114552   
43           15228     15291     15310     15382     15262     15119   
44           45797     46049     46237     46497     46606     46533   
45            8443      8499      8503      8527      8504      8470   
46           62011     62420     62510     62752     62861     62871   

           20191231  20200131  20200229  20200331   20200430  20200531  \
MUNICIPIO                                                                
1             67463     65505     66245     66750    66736.0     68057   
2             93970     91712     92759     93343    93340.0     94967   
3            128978    125884    127461    128544   128543.0    130720   
4             49818     48907     49311     49596    49596.0     50283   
5             68218     66789     67553     68063    68058.0     69125   
6              4200      4145      416

#### Crear un arreglo de los datos de la tabla df_mpo

In [36]:
municipios=np.asarray(df_mpo) 

In [37]:
municipios[0][:-1]

array([66624., 66974., 67275., 67427., 67541., 67450., 67463., 65505.,
       66245., 66750., 66736., 68057., 68054., 68052., 68093., 68244.,
       68241., 68422.])

In [38]:
municipios[0]

array([66624., 66974., 67275., 67427., 67541., 67450., 67463., 65505.,
       66245., 66750., 66736., 68057., 68054., 68052., 68093., 68244.,
       68241., 68422., 68611.])

#### Prediccion de lista nominal 

In [39]:
fits=[]
prediction_lnal=[]

for i in range(len(municipios)):
    xx=np.arange(len(municipios[i]))
    ma, ba = np. polyfit(xx, municipios[i],1,w=municipios[i])
    fits.append([ma,ba])
    pred=ma*(xx[-12]+12)+ba
    #if pred < municipios[i][-1]:
    #    pred=municipios[i][-1]

    prediction_lnal.append(pred)

In [40]:
fits

[[94.25419224188313, 66624.08614573615],
 [152.45706373364425, 92842.89945085235],
 [331.95153702188526, 126455.15743038947],
 [92.3125638319272, 49056.18788898468],
 [172.99838030130135, 66848.4213675266],
 [3.90463768777424, 4184.915707012734],
 [694.7935900212271, 373631.3062443126],
 [68.81576406743835, 30965.975888191057],
 [114.47376444282905, 59426.9447628608],
 [12.662197356581446, 9197.664547790124],
 [131.97324172102898, 73381.36427394292],
 [43.172454891161124, 22975.840546114254],
 [33.031508366954874, 18104.618908092816],
 [247.56055345663592, 111871.32150533395],
 [320.97578919455185, 137106.874489432],
 [12.615533280987927, 16714.67145435467],
 [932.4325823847304, 416640.7119008744],
 [59.72457417690901, 28500.95747115201],
 [65.08872169238008, 40393.24729762477],
 [2758.6641387178283, 1118396.7009228377],
 [79.72573696794458, 42813.06254677173],
 [36.326424299869394, 17798.05879014028],
 [229.07741327570568, 122756.15100835978],
 [13.781502634457865, 10655.772940626823]

#### Agregar la prediccion a la lista nominal

In [42]:
df_mpo['Prediction LNAL']= prediction_lnal

In [43]:
df_mpo

LISTA  20190731  20190831  20190930  20191031  20191130  \
MUNICIPIO                                                              
1            66624     66974     67275     67427     67541     67450   
2            92979     93375     93738     94040     94139     93825   
3           126219    127148    127860    128446    128937    128731   
4            48883     49261     49434     49656     49787     49699   
5            66488     67064     67584     67868     68120     67992   
6             4201      4221      4183      4207      4228      4203   
7           372677    375386    377278    378361    379387    378139   
8            30673     31268     31394     31431     31546     31501   
9            59355     59789     60069     60267     60366     60337   
10            9135      9202      9248      9283      9315      9288   
11           73088     73435     73955     74256     74574     74297   
12           22958     23020     23094     23212     23288     23300   
13           18129     18191     18281     18343     18396     18303   
14          111277    112192    112769    113311    113789    113675   
15          136478    137629    138506    139096    139676    139382   
16           16701     16750     16767     16845     16890     16862   
17          415356    418486    420740    422390    423691    422665   
18           28432     28587     28707     28858     28921     28920   
19           40350     40558     40715     40842     40902     40795   
20         1113418   1122721   1129193   1133923   1138154   1136414   
21           42608     42987     43185     43380     43456     43433   
22           17766     17854     17930     18031     18109     18125   
23          123101    124014    124137    124650    124160    123825   
24           10652     10677     10713     10761     10795     10782   
25           54088     54480     54684     54907     55054     55055   
26           45105     45584     45781     45974     46145     46109   
27          210028    211209    212069    212781    213140    212706   
28           82647     83044     83231     83494     83556     83394   
29           27442     27665     27794     27934     27986     27964   
30           80728     81238     81663     82003     82168     82163   
31           91316     92001     92405     92714     92921     92945   
32           59512     59955     60279     60509     60695     60551   
33           88843     89510     89925     90167     90447     90169   
34            4399      4424      4403      4433      4458      4444   
35           60058     60381     60629     60975     61098     61027   
36            6439      6479      6482      6493      6499      6495   
37          134728    135909    136624    137162    137655    137397   
38           10034     10098     10170     10198     10240     10230   
39           30596     30781     30932     31068     31107     31001   
40           13128     13207     13253     13314     13225     13108   
41           48136     48542     48732     48972     49213     49128   
42          112730    113491    114029    114362    114729    114552   
43           15228     15291     15310     15382     15262     15119   
44           45797     46049     46237     46497     46606     46533   
45            8443      8499      8503      8527      8504      8470   
46           62011     62420     62510     62752     62861     62871   

           20191231  20200131  20200229  20200331   20200430  20200531  \
MUNICIPIO                                                                
1             67463     65505     66245     66750    66736.0     68057   
2             93970     91712     92759     93343    93340.0     94967   
3            128978    125884    127461    128544   128543.0    130720   
4             49818     48907     49311     49596    49596.0     50283   
5             68218     66789     67553     68063    68058.0     69125   
6              4200      4145      416

#### Calcular la tasa de cambio

In [48]:
Tasa_cambio =[]
for i in range(len(municipios)):
    if i == 0:
        change = 0
    else:
        change = abs(prediction_lnal[i]-municipios[i,18])/municipios[i,18]
    Tasa_cambio.append([change])

In [52]:
Tasa_cambio

In [51]:
data1=pd.read_csv('DatosAbiertos-derfe-pdln_edms_sexo_20201231_Nal_Ext.txt',usecols=("ENTIDAD","DISTRITO","MUNICIPIO","SECCION","TOTAL_LISTA"))
data1=data1[data1['ENTIDAD']==11]


In [53]:
valores =[] #Arreglo donde se van a guardar solo los valores de las columnas
for i in range(len(Tasa_cambio)): 
    dataMPO=data1[data1['MUNICIPIO']==i] 
    A_dataMPO=np.asarray(dataMPO) 
    valores.append(A_dataMPO)  


In [63]:
valores[45]

array([[  11,    1,   45, 2934,  410],
       [  11,    1,   45, 2935, 1636],
       [  11,    1,   45, 2936,  312],
       [  11,    1,   45, 2937,  449],
       [  11,    1,   45, 2938,  407],
       [  11,    1,   45, 2939,  332],
       [  11,    1,   45, 2940, 1059],
       [  11,    1,   45, 2941,  369],
       [  11,    1,   45, 2942,  928],
       [  11,    1,   45, 2943,  770],
       [  11,    1,   45, 2944,  711],
       [  11,    1,   45, 2945,  420],
       [  11,    1,   45, 2946,  429],
       [  11,    1,   45, 2948,  355]], dtype=int64)

# .....